const translations = {
    en: {
        brandName: "Valentin Kolesnikov",

        themeBtn: "Theme",
        backBtn: "← Back to Main Menu",
        githubBtn: "View on GitHub",
        home: "About Me",
        musicBtn: "Music",
        
        aboutText: "Welcome. I am Valentin Kolesnikov. I specialize in Python development, algorithms, and data analysis tools. Explore my key projects below to see my code in action.",
        ytShort: "Deep data analysis tool for YouTube content.",
        rpsShort: "Advanced implementation of the classic game.",
        rsaShort: "Custom implementation of RSA encryption.",
        notepadShort: "Simple desktop text editor built with Python.",
        ytDesc1: "YouTube Explorer is a comprehensive tool designed for content creators and analysts. It bypasses the limitations of the standard YouTube interface to provide deep insights into video metadata.",
        ytDesc2: "Key capabilities include extracting hidden tags, analyzing engagement metrics in real-time, and filtering content based on advanced parameters not available on the web version.",
        ytDesc3: "The project focuses on speed and accuracy, utilizing efficient algorithms to process large datasets of video information.",
        rpsDesc1: "A robust implementation of the classic game 'Rock, Paper, Scissors'. This project demonstrates clean code structure, user input handling, and game logic state management.",
        rpsDesc2: "It serves as a perfect example of algorithmic thinking applied to simple interactive systems, ensuring edge cases are handled and the user experience is smooth.",
        rsaDesc1: "A custom implementation of the RSA (Rivest–Shamir–Adleman) public-key cryptosystem. This project explores the mathematical foundations of modern web security.",
        rsaDesc2: "It includes key generation (public and private), encryption of messages, and decryption processes, providing a transparent view into how secure data transmission works.",
        notepadDesc1: "A lightweight and efficient text editor designed for speed and simplicity. Built with Python, it mirrors the classic functionality of standard notepads but with a cleaner codebase.",
        notepadDesc2: "Features include creating, opening, and saving text files, as well as essential editing tools. It serves as a practical example of building desktop GUI applications.",

        ye_meta: "Python • Terminal-app • Data parsing",
        ye_title_main: "YouTube Explorer",
        ye_intro: "<strong>YouTube Explorer</strong> is a console-based Python tool for programmatic exploration of YouTube content using <strong>YouTube Data API v3</strong> (with OAuth 2.0 support), <strong>Return YouTube Dislike API</strong>, and <strong>YouTube Transcript API</strong>",
        ye_caution: "<strong>CAUTION:</strong> The official repository is only available on my <a href='https://github.com/valentin-kolesnikov/YouTube_Explorer'>GitHub</a>. Any clones distributed on my behalf on other platforms are not my work.",
        ye_warning: "<strong>WARNING:</strong> Some antivirus software may flag the app as a potentially unwanted program (PUP). This is a false positive. All materials used for the app are stored in the public repository. As a developer, I have no desire to harm other users. You can always contact me via email for such issues.",
        ye_designed_for: "It is designed for:",
        ye_list_1: "Working within YouTube API quota limits",
        ye_list_2: "Retrieving and filtering comments",
        ye_list_3: "Searching videos and retrieving playlists",
        ye_list_4: "Extracting metadata",
        ye_list_5: "Collecting subtitles",
        
        toc_title: "🗒️Table of Contents",
        toc_toc: "🗒️Table of Contents",
        toc_req: "❗Requirements",
        toc_down: "🌐How to download?",
        toc_apikey: "❓How to get the YouTube Data API v3 key?",
        toc_oauth: "🛡️ How to get OAuth 2.0 credentials?",
        toc_core: "Core capabilities",
        toc_core_key: "🔑YouTube API key handling",
        toc_core_quota: "🚪Quota inspection",
        toc_core_comment: "💌Comment Explorer",
        toc_core_video: "📹Video Explorer",
        toc_core_channel: "📈Channel Explorer",
        toc_play: "🗂️Playlist Explorer",
        toc_core_subs: "📄Subtitles Explorer",
        toc_core_info: "🔢Info Explorer",
        toc_func: "⚙️ Functionality",
        toc_license: "🖌️License",
        toc_contrib: "❤️Contributing",
        toc_how: "🤝How to contribute",
        toc_don: "💰Donations",
        toc_issues: "❓Issues",

        req_title: "❗Requirements",
        req_p: "To use YouTube Explorer, you need the following:",
        req_li_1: "Your desire to use <strong>YouTube Explorer</strong>",
        req_li_2: "A valid YouTube Data API v3 key issued via Google Cloud Console",
        req_li_3: "Python 3.10 or newer (required when running from the repository)",
        req_li_4: "A stable Internet connection",
        req_note: "Basic familiarity with command-line usage is recommended.",

        down_title: "🌐How to download?",
        down_rel_title: "Releases",
        down_win: "Windows:",
        down_rel_w1: "<code class='inline-code'>Releases</code> → <code class='inline-code'>YouTubeExplorer.zip</code>",
        down_rel_w2: "Extract the <code class='inline-code'>.zip</code> folder",
        down_rel_w3: "<code class='inline-code'>bin</code> → open <code class='inline-code'>YouTubeExplorer.exe</code>",
        down_ub: "Ubuntu-like:",
        down_rel_u1: "<strong>Releases</strong> → <code class='inline-code'>YouTubeExplorer.tar.gz</code>",
        down_rel_u2: "Extract the <code class='inline-code'>.tar.gz</code> folder",
        down_rel_u3: "YouTubeExplorer.dist → Copy <code class='inline-code'>YouTubeExplorer.bin</code> → Paste it into the terminal and press Enter, or run it via command: <code class='inline-code'>./YouTubeExplorer.bin</code>",
        down_git_title: "Git",
        down_git_1: "Install <code class='inline-code'>Git</code>",
        down_git_2: "In the terminal, paste: <code class='inline-code'>git clone https://github.com/valentin-kolesnikov/YouTube_Explorer</code>",
        down_git_3: "Map to the folder and run the main script <code class='inline-code'>YouTubeExplorer.py</code>",
        down_git_4: "Type <code class='inline-code'>pip install -r requirements.txt</code> in the terminal to install all dependencies",

        api_title: "❓How to get the YouTube Data API v3 key?",
        api_li_1: "Go to the <a href='https://console.cloud.google.com' target='_blank' rel='noopener noreferrer'>Google Cloud Console</a>",
        api_li_2: "You need to register for a Google account or log in to it.",
        api_li_3: "Click the <strong>Create or select a project</strong> button in the center of the page → <strong>New project</strong>",
        api_li_4: "Enter a project name (or leave the auto-generated one). → If you do not belong to an organisation, leave the <strong>Location</strong> as default. → Click <strong>Create</strong>.",
        api_li_5: "On the same page, click <strong>Select project</strong> and choose your project. Type <code class='inline-code'>YouTube Data API v3</code> in the search bar → click <strong>Enable</strong>",
        api_li_6: "You will be redirected to the API configuration. In the left column, you should press <strong>Credentials</strong>.",
        api_li_7: "At the top, click <strong>Create credentials</strong> → <strong>API key</strong>.",
        api_li_8: "That is it! Copy your API key and paste it into YouTube Explorer. If you need, you can restore the key from the main menu.",

        oauth_title: "🛡️ How to get OAuth 2.0 credentials?",
        oauth_intro_1: "The application is designed to use <strong>OAuth 2.0</strong> as the primary authentication method",
        oauth_intro_2: "If OAuth client secrets are not found, the system switches to the <strong>YouTube Data API Key</strong> method without interrupting the user",
        oauth_intro_3: "Since automated OAuth 2.0 registration isn't supported out-of-the-box, you will need to generate your own credentials by following these steps:",
        oauth_li_1: "Go to the <a href='https://console.cloud.google.com' target='_blank' rel='noopener noreferrer'>Google Cloud Console</a>.",
        oauth_li_2: "Select the project you already created for your YouTube Data API v3 key.",
        oauth_li_3: "In the left column, click <strong>OAuth consent screen</strong>.",
        oauth_li_4: "Choose <strong>External</strong> as the User Type and click <strong>Create</strong>.",
        oauth_li_5: "Fill in the required fields: <code class='inline-code'>App name</code>, <code class='inline-code'>User support email</code>, and <code class='inline-code'>Developer contact information</code> (you can use your own email for all of these). Click <strong>Save and Continue</strong>.",
        oauth_li_6: "Skip the <strong>Scopes</strong> page by clicking <strong>Save and Continue</strong>.",
        oauth_li_7: "On the <strong>Test users</strong> page, click <strong>Add Users</strong> and type in your own Google account email. Click <strong>Save and Continue</strong>.",
        oauth_li_8: "Now, click on <strong>Credentials</strong> in the left column again.",
        oauth_li_9: "At the top, click <strong>Create credentials</strong> → <strong>OAuth client ID</strong>.",
        oauth_li_10: "Select <strong>Desktop app</strong> as the Application type. You can leave the default name. Click <strong>Create</strong>.",
        oauth_li_11: "A window will pop up. Click <strong>Download JSON</strong> to save your credentials.",
        oauth_li_12: "The downloaded <code class='inline-code'>.json</code> file must be placed in the <code class='inline-code'>Keys</code> folder of the <code class='inline-code'>bin</code> folder.",

        core_title: "Core capabilities",
        key_title: "🔑YouTube API key handling",
        key_li_1: "Initial validation of the provided API key before execution",
        key_li_2: "Automatic creation and storage of a <code class='inline-code'>Key.bin</code> file",
        key_li_3: "Exclusion of re-entering the key after successful verification",

        quota_title: "🚪Quota inspection",
        quota_li_1: "Detects current availability of the YouTube API quota",
        quota_li_2: "Stops execution if further requests are not possible",

        comm_title: "💌Comment Explorer",
        comm_li_1: "Get a list of comments on YouTube videos in the console",
        comm_li_2: "Filter comments by keyword",
        comm_li_3: "Sort <code class='inline-code'>by time</code> or <code class='inline-code'>by relevance</code>",
        comm_li_4: "Limit the number of output results",
        comm_li_5: "Identify the channel hosting the video",
        comm_li_7: "NEW! Comment Explorer can save the collected data in a <code class='inline-code'>.docx</code> file",

        vid_title: "📹Video Explorer",
        vid_li_1: "Search for videos by your prompt",
        vid_li_2: "Perform region-specific searches",
        vid_li_3: "Apply optional filters such as: <code class='inline-code'>publication date range</code> and <code class='inline-code'>video duration</code>",
        vid_li_4: "Control the maximum number of returned search results",
        vid_li_5: "For each video, you will receive the following metadata:",
        vid_sub_1: "The title of the video",
        vid_sub_2: "Direct URL",
        vid_sub_3: "View count",
        vid_sub_4: "Like count",
        vid_sub_5: "Dislike count",
        vid_sub_6: "Comment count",
        vid_sub_7: "Publication date",
        vid_sub_8: "Channel name and channel URL",

        chan_title: "📈Channel Explorer",
        chan_li_1: "Collect most of the channel statistics:",
        chan_sub_1: "Subscriber count",
        chan_sub_2: "View count",
        chan_sub_3: "Description",
        chan_sub_4: "Registration date",
        chan_sub_5: "Channel ID (UC...)",
        chan_sub_6: "Handle (@...)",
        chan_li_2: "If necessary, you can search videos on the certain channel thanks to the Video Explorer components",

        play_title: "🗂️Playlist Explorer",
        play_li_1: "Search for playlists using keywords, or securely load <strong>your own</strong> playlists using OAuth 2.0",
        play_li_2: "View basic playlist details, such as privacy status, total video count, and publication date",
        play_li_3: "Easily extract all videos from any playlist by entering its URL (supports both <code class='inline-code'>PL...</code> and <code class='inline-code'>OL...</code> links)",
        play_li_4: "Get detailed statistics for every video inside the playlist, complete with dislike counts",
        play_li_5: "Analyze a playlist's video library right after finding it, without needing to go back to the main menu",

        subs_title: "📄Subtitles Explorer",
        subs_li_1: "<strong>Subtitles Explorer</strong> makes extracting text from videos effortless and flexible. You enter the two-letter language codes, such as <code class='inline-code'>en</code> or <code class='inline-code'>ru</code>",
        subs_li_2: "It gives you the choice between <code class='inline-code'>manually created</code> subtitles for better accuracy or <code class='inline-code'>auto-generated</code> transcripts. The system is designed to handle missing data intelligently",
        subs_li_3: "If your preferred transcript type is not available, it will not just show an error and stop. Instead, it detects the issue and offers the alternative version immediately, ensuring you can still retrieve the content you are looking for.",

        info_title: "🔢Info Explorer",
        info_li_1: "Enter a specific video URL to directly extract metadata without searching",
        info_li_2: "Returns the complete information block detailed in <a href='#video-explorer'>Video Explorer</a> and, additionally, the video description",

        func_title: "⚙️ Functionality",
        func_li_1: "<strong>Authentication</strong> — <strong>OAuth 2.0</strong> is prioritised for secure access. If OAuth credentials are not detected, the application uses the <strong>YouTube Data API key</strong> stored in <code class='inline-code'>Key.bin</code>",
        func_li_2: "<strong>Link parsing</strong> — <code class='inline-code'>video id</code>, <code class='inline-code'>channel id</code> (UC...), and <code class='inline-code'>handle</code> (@...) are automatically extracted from the links you enter",
        func_li_3: "<strong>Search filters</strong> — you can filter videos by <code class='inline-code'>Region</code>, <code class='inline-code'>Dimension</code> (2D or 3D), <code class='inline-code'>Duration</code>, and <code class='inline-code'>Date</code> (using the smart calendar)",
        func_li_4: "<strong>Channel search</strong> — unlike standard search, you can perform keyword searches specifically inside a channel's library",
        func_li_5: "<strong>Smart Subtitles</strong> — <strong>YouTube Transcript API</strong> is integrated. It looks for <code class='inline-code'>manually created</code> subtitles first. If they are missing, it asks if you want <code class='inline-code'>auto-generated</code> ones",
        func_li_6: "<strong>Dislikes</strong> — <strong>Return YouTube Dislike API</strong> is integrated to show dislike counts mixed with official data",
        func_li_7: "<strong>Comment filtering</strong> — <strong>Keywords</strong> are used to filter comments and replies locally. YouTube Data API does not do this filtering",
        func_li_8: "<strong>Quota check</strong> — a test request is made at the start to ensure your <strong>YouTube API quota</strong> is not exceeded before running",
        func_li_9: "<strong>Automatic verification</strong> — before making API requests, YouTube Explorer pings <code class='inline-code'>google.com</code> to ensure your connection is active. If the connection is lost, you can retry connecting",
        func_li_10: "Receive detailed error messages if something goes wrong",
        func_li_11: "Now the main menu consists of two pages",
        func_li_12: "Restore your <strong>YouTube API</strong> key on the second page of the main menu",

        lic_title: "🖌️License",
        lic_p1: "YouTube Explorer is licensed under the <code class='inline-code'>GNU GPL-3.0</code>.",
        lic_p2: "Versions released before 22-01-2026 were licensed under the <code class='inline-code'>MIT License</code>.",
        lic_p_new: "Versions released before 20.05.2026 were licensed under the <code class='inline-code'>Apache-2.0 license</code>",
        lic_p3: "Author: Valentin Kolesnikov",
        lic_p4: "Original repository: <a href='https://github.com/valentin-kolesnikov/YouTube_Explorer'>YouTube_Explorer</a>",
        lic_p5: "For more details, see the <a href='LICENSE'>LICENSE</a> and <a href='ABOUT'>ABOUT</a> files.",

        contr_title: "❤️Contributing",
        contr_p1: "Thank you for your interest in contributing to this project.",
        contr_p2: "This project is licensed under the <strong>General Public License 3.0</strong>. By submitting a pull request, you agree that your contribution will be licensed under the <code class='inline-code'>GPL-3.0</code>.",
        contr_p3: "If you create a fork or derivative work based on this project, please provide clear attribution in your <code class='inline-code'>README</code>.",
        contr_p4: "A recommended attribution format is:",
        contr_p5: "<strong>Original project: YouTube Explorer by Valentin Kolesnikov</strong>",
        contr_p6: "This attribution helps avoid confusion about authorship and is considered good open-source practice.",

        how_title: "🤝How to contribute",
        how_li_1: "Fork the repository.",
        how_li_2: "Create a branch for your change.",
        how_li_3: "Submit a pull request with a clear description.",
        how_li_4: "Make sure your changes are well documented.",

        don_title: "💰Donations",
        don_p: "If you really want to support me, here is the link: <a href='https://www.donationalerts.com/r/valera_koleso' target='_blank' rel='noopener noreferrer'><code class='inline-code'>DonationAlerts</code></a>",

        iss_title: "❓Issues",
        iss_p: "I will be glad to see your opinions and ideas for new features or improvements. Moreover, please report bugs. Just open <strong>Issues</strong> and surprise me!",
        
        rps_title_new: "Rock Paper Scissors",
        rps_meta: "Game Logic • Python • Interactive",
        rps_intro_new: "A simple Python implementation of the classic Rock Paper Scissors game. Play against one or two computer opponents in a text-based interface.",
        rps_feat_title: "Features",
        rps_feat_1: "Terminal-based gameplay.",
        rps_feat_2: "Play against one computer or two computers.",
        rps_feat_3: "Any number of rounds with repeated draws until someone wins.",
        rps_feat_4: "Randomized (used math.ceil; secrets.choice from the list which will be created by random.uniform) computer moves.",
        rps_feat_5: "Clear scoring system and round tracking.",
        rps_how_title: "How to Play",
        rps_how_1: "Open the <code class='inline-code'>.exe</code> file or <code class='inline-code'>.py</code> file.",
        rps_how_2: "At the start, choose whether you want to play.",
        rps_how_3: "Select the number of players: <code class='inline-code'>1</code> (you against the computer) or <code class='inline-code'>2</code> (you against two computers).",
        rps_how_4: "You can choose any number of rounds you want.",
        rps_how_5: "Choose a move: a rock - number <code class='inline-code'>1</code>; a paper - number <code class='inline-code'>2</code>; scissors - number <code class='inline-code'>3</code>.",
        rps_how_6: "The game continues until victory in each round; a draw restarts the move.",
        rps_how_7: "The announcement of the winner will keep track of who has what points, and then give the opportunity to win back (even to computers, if the player has definitely lost) if someone has a draw.",
        rps_note: "I've completed the project! If I find errors, I will fix them as small fixes. However, they should not be.",

        rsa_title_main: "Python RSA",
        rsa_meta: "Cryptography • Mathematics • Experimental",
        rsa_intro: "The script allows you to encrypt and decrypt a message using a pair of prime numbers.",
        rsa_clarif_title: "Important clarification",
        rsa_clarif_text: "The .exe file is in releases. This <code class='inline-code'>.exe</code> file does not have viruses. It was created for convenience. I made this file thanks to <code class='inline-code'>python -m PyInstaller --onefile ...</code>. If you do not trust the <code class='inline-code'>.exe</code> file, I recommend you to use the <code class='inline-code'>.py</code> file.",
        rsa_func_title: "Functionality",
        rsa_func_list: "<li>Entering a message (English or Russian, you choose).</li> <li>Conversion to numeric format.</li> <li>Key generation (p, q, d, e).</li> <li>Encryption and decryption.</li> <li>Display of intermediate steps.</li>",
        rsa_work_title: "How does it work?",
        rsa_work_list: "<li>Open the <code class='inline-code'>.exe</code> file or <code class='inline-code'>.py</code> file.</li> <li>You choose English or Russian. 1 or 2, respectively.</li> <li>Write the message (one word). You can write uppercase and lowercase letters.</li> <li>Choose the prime number p that you want.</li> <li>Choose the prime number q that is greater than p. Warning: this code doesn't accept a combination of (p;q), respectively: (2;3),(2;5),(2;7),(3;5). The program will ask you to choose other numbers.</li> <li>The program calculates all the values using formulas and outputs an encrypted message and decrypts it at the same time.</li>",
        rsa_warn_title: "Important: this implementation is intended for educational purposes. Do not use it in production or in real security systems.",
        
        lb_title: "Like a Notepad",
        lb_meta: "Productivity • Python • CLI Tool",
        lb_intro: "<p>This is a simple Python script that interactively collects and displays a list of entries from the user. It supports two modes:</p>",
        lb_list: "<li>Main Info only</li> <li>Main + Additional Info</li> <li>Ideal for quickly gathering structured data from user input.</li>",
        lb_clarif_title: "Important clarification",
        lb_clarif_text: "The <code class='inline-code'>.exe</code> file is in releases. This <code class='inline-code'>.exe</code> file does not have viruses. It was created for convenience. I made this file thanks to <code class='inline-code'>python -m PyInstaller --onefile ...</code>. If you do not trust the <code class='inline-code'>.exe</code> file, I recommend you to use the <code class='inline-code'>.py</code> file.",
        lb_feat_title: "Features",
        lb_feat_list: "<li>Interactive CLI prompts</li> <li>Two input modes (basic or with additional details)</li> <li>Custom stop-words to end input session</li> <li>Neat and numbered output formatting</li>",
        lb_how_title: "How to use?",
        lb_how_list: "<li>Open the <code class='inline-code'>.exe</code> file or <code class='inline-code'>.py</code> file.</li> <li>Choose mode: 1 = main info only; 2 = main + additional info.</li> <li>To stop input, type: <code class='inline-code'>stop</code>, <code class='inline-code'>enough</code>, <code class='inline-code'>yes</code>, <code class='inline-code'>-</code> or pressing <code class='inline-code'>Enter</code>.</li> <li>The script will output your entries as a formatted, numbered list.</li>",
        lb_footer: "I have completed this project. If I find errors, I will fix them as small fixes. However, they should not be."
    },
    ru: {
        brandName: "Валентин Колесников",

        themeBtn: "Тема",
        backBtn: "← На Главную",
        githubBtn: "Смотреть на GitHub",
        home: "Обо мне",
        musicBtn: "Музыка",

        aboutText: "Приветствую. Я Валентин Колесников. Я специализируюсь на разработке Python, алгоритмах и инструментах анализа данных. Изучите мои ключевые проекты ниже.",
        ytShort: "Инструмент глубокого анализа данных YouTube.",
        rpsShort: "Продвинутая реализация классической игры.",
        rsaShort: "Кастомная реализация шифрования RSA.",
        notepadShort: "Простой текстовый редактор на Python.",
        ytDesc1: "YouTube Explorer — это комплексный инструмент для создателей контента и аналитиков. Позволяет получать глубокие инсайты о видео.",
        ytDesc2: "Ключевые возможности включают извлечение скрытых тегов и анализ метрик вовлеченности в реальном времени.",
        ytDesc3: "Проект сфокусирован на скорости и точности, используя эффективные алгоритмы для обработки больших данных.",
        rpsDesc1: "Надежная реализация классической игры 'Камень, Ножницы, Бумага'. Демонстрирует чистый код и управление состоянием.",
        rpsDesc2: "Служит отличным примером алгоритмического мышления в интерактивных системах и обработки пользовательского ввода.",
        rsaDesc1: "Кастомная реализация криптосистемы RSA. Исследует математические основы современной безопасности.",
        rsaDesc2: "Включает генерацию ключей, шифрование и дешифрование, показывая, как работает безопасная передача данных.",
        notepadDesc1: "Легкий и эффективный текстовый редактор, созданный для скорости и простоты. Написан на Python.",
        notepadDesc2: "Функции включают создание, открытие и сохранение файлов. Практический пример создания GUI-приложений.",

        ye_meta: "Python • Терминал • Извлечение данных",
        ye_title_main: "YouTube Explorer",
        ye_intro: "<strong>YouTube Explorer</strong> — это консольный инструмент на Python для программного исследования контента YouTube с использованием <strong>YouTube Data API v3</strong> (с поддержкой OAuth 2.0), <strong>Return YouTube Dislike API</strong> и <strong>YouTube Transcript API</strong>.",
        ye_caution: "<strong>ВНИМАНИЕ:</strong> Официальный репозиторий доступен только на моем <a href='https://github.com/valentin-kolesnikov/YouTube_Explorer'>GitHub</a>. Любые клоны, распространяемые от моего имени на других платформах, не являются моей работой.",
        ye_warning: "<strong>ПРЕДУПРЕЖДЕНИЕ:</strong> Некоторое антивирусное программное обеспечение может помечать приложение как потенциально нежелательную программу (PUP). Это ложное срабатывание антивируса. Все материалы, используемые для приложения, хранятся в публичном репозитории. У меня как разработчика нет желания вредить другим пользователям. Вы всегда можете обратиться ко мне через email по таким вопросам.",
        ye_designed_for: "YouTube Explorer предназначен для:",
        ye_list_1: "Работы в пределах лимитов квоты YouTube API",
        ye_list_2: "Получения и фильтрации комментариев",
        ye_list_3: "Поиска видео и получения плейлистов",
        ye_list_4: "Извлечения метаданных",
        ye_list_5: "Сбора субтитров",
        
        toc_title: "🗒️Оглавление",
        toc_toc: "🗒️Оглавление",
        toc_req: "❗Требования",
        toc_down: "🌐Как скачать?",
        toc_apikey: "❓Как получить ключ YouTube Data API v3?",
        toc_oauth: "🛡️ Как получить учетные данные OAuth 2.0?",
        toc_core: "Основные возможности",
        toc_core_key: "🔑Работа с ключом YouTube API",
        toc_core_quota: "🚪Проверка квоты",
        toc_core_comment: "💌Comment Explorer",
        toc_core_video: "📹Video Explorer",
        toc_core_channel: "📈Channel Explorer",
        toc_play: "🗂️Playlist Explorer",
        toc_core_subs: "📄Subtitles Explorer",
        toc_core_info: "🔢Info Explorer",
        toc_func: "⚙️ Функционал",
        toc_license: "🖌️Лицензия",
        toc_contrib: "❤️Сотрудничество",
        toc_how: "🤝Как внести свой вклад",
        toc_don: "💰Пожертвования",
        toc_issues: "❓Issues",

        req_title: "❗Требования",
        req_p: "Для использования YouTube Explorer вам понадобится следующее:",
        req_li_1: "Ваше желание использовать <strong>YouTube Explorer</strong>",
        req_li_2: "Действительный ключ YouTube Data API v3, выпущенный через Google Cloud Console",
        req_li_3: "Python 3.10 или новее (требуется при запуске из репозитория)",
        req_li_4: "Стабильное интернет-соединение",
        req_note: "Рекомендуется базовое знакомство с использованием командной строки.",

        down_title: "🌐Как скачать?",
        down_rel_title: "Releases",
        down_win: "Windows:",
        down_rel_w1: "<code class='inline-code'>Releases</code> → <code class='inline-code'>YouTubeExplorer.zip</code>",
        down_rel_w2: "Извлеките папку <code class='inline-code'>.zip</code>",
        down_rel_w3: "<code class='inline-code'>bin</code> → откройте <code class='inline-code'>YouTubeExplorer.exe</code>",
        down_ub: "Ubuntu-подобные:",
        down_rel_u1: "<strong>Releases</strong> → <code class='inline-code'>YouTubeExplorer.tar.gz</code>",
        down_rel_u2: "Извлеките папку <code class='inline-code'>.tar.gz</code>",
        down_rel_u3: "YouTubeExplorer.dist → Скопируйте <code class='inline-code'>YouTubeExplorer.bin</code> → Вставьте в терминал и нажмите Enter, или же запустите командой: <code class='inline-code'>./YouTubeExplorer.bin</code>",
        down_git_title: "Git",
        down_git_1: "Установите <code class='inline-code'>Git</code>",
        down_git_2: "В терминале вставьте: <code class='inline-code'>git clone https://github.com/valentin-kolesnikov/YouTube_Explorer</code>",
        down_git_3: "Перейдите в папку и запустите основной скрипт <code class='inline-code'>YouTubeExplorer.py</code>",
        down_git_4: "Введите <code class='inline-code'>pip install -r requirements.txt</code> в терминале, чтобы установить все зависимости программы",

        api_title: "❓Как получить ключ YouTube Data API v3?",
        api_li_1: "Перейдите в <a href='https://console.cloud.google.com' target='_blank' rel='noopener noreferrer'>Google Cloud Console</a>",
        api_li_2: "Вам нужно зарегистрировать аккаунт Google или войти в него.",
        api_li_3: "Нажмите кнопку <strong>Create or select a project</strong> в центре страницы → <strong>New project</strong>.",
        api_li_4: "Введите название проекта (или оставьте сгенерированное автоматически). → Если вы не принадлежите к какой-либо организации, оставьте <strong>Location</strong> по умолчанию. → Нажмите <strong>Create</strong>.",
        api_li_5: "На этой же странице нажмите <strong>Select project</strong> и выберите свой проект. Введите <code class='inline-code'>YouTube Data API v3</code> в строке поиска → нажмите <strong>Enable</strong>.",
        api_li_6: "Вас перенаправит на страницу конфигурации API. В левом столбце нажмите <strong>Credentials</strong>.",
        api_li_7: "Вверху нажмите <strong>Create credentials</strong> → <strong>Ключ API</strong>.",
        api_li_8: "Скопируйте ваш API-ключ и вставьте его в YouTube Explorer. При необходимости вы можете восстановить ключ из главного меню.",

        oauth_title: "🛡️ Как получить учетные данные OAuth 2.0?",
        oauth_intro_1: "Приложение разработано для использования <strong>OAuth 2.0</strong> в качестве основного метода аутентификации",
        oauth_intro_2: "Автоматическое переключение на метод <strong>YouTube Data API Key</strong>, если OAuth-данные отсутствуют",
        oauth_intro_3: "Поскольку автоматическая регистрация OAuth 2.0 не поддерживается из коробки, потребуется сгенерировать собственные учетные данные, выполнив следующие шаги:",
        oauth_li_1: "Перейдите в <a href='https://console.cloud.google.com' target='_blank' rel='noopener noreferrer'>Google Cloud Console</a>.",
        oauth_li_2: "Выберите проект, который вы уже создали для своего ключа YouTube Data API v3.",
        oauth_li_3: "В левом столбце нажмите <strong>OAuth consent screen</strong>.",
        oauth_li_4: "Выберите <strong>External</strong> в качестве типа пользователя и нажмите <strong>Create</strong>.",
        oauth_li_5: "Заполните обязательные поля: <code class='inline-code'>App name</code>, <code class='inline-code'>User support email поддержки</code> и <code class='inline-code'>Developer contact information</code> (можно использовать свою собственную электронную почту). Нажмите <strong>Save and Continue</strong>.",
        oauth_li_6: "Пропустите страницу <strong>Scopes</strong>, нажав <strong>Save and Continue</strong>.",
        oauth_li_7: "На странице <strong>Test users</strong> нажмите <strong>Add Users</strong> и введите адрес электронной почты своего аккаунта Google. Нажмите <strong>Save and Continue</strong>.",
        oauth_li_8: "Теперь снова нажмите <strong>Credentials</strong> в левом столбце.",
        oauth_li_9: "Вверху нажмите <strong>Create credentials</strong> → <strong>OAuth client ID</strong>.",
        oauth_li_10: "Выберите <strong>Desktop app</strong> в качестве типа приложения. Вы можете оставить имя по умолчанию. Нажмите <strong>Create</strong>.",
        oauth_li_11: "Появится всплывающее окно. Нажмите <strong>Download JSON</strong>, чтобы сохранить ваши учетные данные.",
        oauth_li_12: "Скачанный файл <code class='inline-code'>.json</code> необходимо поместить в папку <code class='inline-code'>Keys</code>, которая находится в папке <code class='inline-code'>bin</code>.",

        core_title: "Основные возможности",
        key_title: "🔑Работа с ключом YouTube API",
        key_li_1: "Первоначальная проверка предоставленного API-ключа перед выполнением",
        key_li_2: "Автоматическое создание и сохранение файла <code class='inline-code'>Key.bin</code>",
        key_li_3: "Исключение повторного ввода ключа после успешной проверки",

        quota_title: "🚪Проверка квоты",
        quota_li_1: "Определяет текущую доступность квоты YouTube API",
        quota_li_2: "Останавливает выполнение, если дальнейшие запросы невозможны",

        comm_title: "💌Comment Explorer",
        comm_li_1: "Получайте список комментариев к видео на YouTube в консоли",
        comm_li_2: "Фильтруйте комментарии по ключевому слову",
        comm_li_3: "Сортируйте <code class='inline-code'>по времени</code> (by time) или <code class='inline-code'>по релевантности</code> (by relevance)",
        comm_li_4: "Ограничивайте количество выводимых результатов",
        comm_li_5: "Определяйте канал, на котором размещено видео",
        comm_li_7: "НОВЕЙШЕЕ! Comment Explorer может сохранять собранные данные в файл <code class='inline-code'>.docx</code>",

        vid_title: "📹Video Explorer",
        vid_li_1: "Ищите видео по вашему запросу",
        vid_li_2: "Выполняйте поиск с учетом региона",
        vid_li_3: "Применяйте дополнительные фильтры, такие как: <code class='inline-code'>диапазон дат публикации</code> и <code class='inline-code'>длительность видео</code>",
        vid_li_4: "Контролируйте максимальное количество возвращаемых результатов поиска",
        vid_li_5: "Для каждого видео вы получите следующие метаданные:",
        vid_sub_1: "Название видео",
        vid_sub_2: "Прямая ссылка",
        vid_sub_3: "Количество просмотров",
        vid_sub_4: "Количество лайков",
        vid_sub_5: "Количество дизлайков",
        vid_sub_6: "Количество комментариев",
        vid_sub_7: "Дата публикации",
        vid_sub_8: "Название канала и ссылка на канал",

        chan_title: "📈Channel Explorer",
        chan_li_1: "Собирайте большую часть статистики канала:",
        chan_sub_1: "Количество подписчиков",
        chan_sub_2: "Количество просмотров",
        chan_sub_3: "Описание",
        chan_sub_4: "Дата регистрации",
        chan_sub_5: "ID канала (UC...)",
        chan_sub_6: "Имя пользователя (Handle) (@...)",
        chan_li_2: "При необходимости у вас есть возможность искать видео на опрделённом канале благодаря компонентам Video Explorer",

        play_title: "🗂️Playlist Explorer",
        play_li_1: "Ищите плейлисты с помощью ключевых слов или безопасно загружайте <strong>свои собственные</strong> плейлисты, используя OAuth 2.0",
        play_li_2: "Просматривайте основные сведения о плейлисте, такие как статус конфиденциальности, общее количество видео и дата публикации",
        play_li_3: "Легко извлекайте все видео из любого плейлиста, просто введя его URL (поддерживаются ссылки как <code class='inline-code'>PL...</code>, так и <code class='inline-code'>OL...</code>)",
        play_li_4: "Получайте подробную статистику для каждого видео внутри плейлиста, включая количество дизлайков",
        play_li_5: "Анализируйте видеотеку плейлиста сразу после его нахождения, без необходимости возвращаться в главное меню",

        subs_title: "📄Subtitles Explorer",
        subs_li_1: "<strong>Subtitles Explorer</strong> может извлечь субтитры из видео без всяких усилий. Введите двухбуквенный код языка (<code class='inline-code'>en</code>, <code class='inline-code'>ru</code> и т.д.)",
        subs_li_2: "Выберите между <code class='inline-code'>созданными вручную</code> для большей точности и <code class='inline-code'>автоматическими</code> субтитрами, если субтитров, сделанных вручную, не окажется. Автоматическое предложение альтернативы при отсутствии выбранного типа",
        subs_li_3: "Если тип расшифровки недоступен, программа не выдаст ошибку и не прекратит работу. Вместо этого она обнаружит проблему и сразу предложит альтернативную версию, чтобы вы смогли получить желаемое.",

        info_title: "🔢Info Explorer",
        info_li_1: "Введите URL-адрес конкретного видео, чтобы напрямую извлечь метаданные без поиска",
        info_li_2: "Возвращает полный блок информации, описанный в <a href='#video-explorer'>Video Explorer</a>, а также описание видео",

        func_title: "⚙️ Функционал",
        func_li_1: "<strong>Аутентификация</strong> — <strong>OAuth 2.0</strong> имеет приоритет для безопасного доступа. Если учетные данные OAuth не обнаружены, приложение использует <strong>YouTube Data API key</strong>, сохраненный в <code class='inline-code'>Key.bin</code>",
        func_li_2: "<strong>Парсинг ссылок</strong> — <code class='inline-code'>video id</code>, <code class='inline-code'>channel id</code> (UC...) и <code class='inline-code'>имя пользователя</code> (@...) автоматически извлекаются из введенных вами ссылок",
        func_li_3: "<strong>Фильтры поиска</strong> — вы можете фильтровать видео по <code class='inline-code'>Региону</code> (Region), <code class='inline-code'>Измерению</code> (Dimension) (2D или 3D), <code class='inline-code'>Длительности</code> (Duration) и <code class='inline-code'>Дате</code> (Date)",
        func_li_4: "<strong>Поиск по каналу</strong> — в отличие от стандартного поиска, вы можете выполнять поиск по ключевым словам непосредственно внутри библиотеки канала",
        func_li_5: "<strong>Умные субтитры</strong> — интегрирован <strong>YouTube Transcript API</strong>. Сначала он ищет <code class='inline-code'>созданные вручную</code> (manually created) субтитры. Если они отсутствуют, он спросит, хотите ли вы получить <code class='inline-code'>автоматически сгенерированные</code> (generated)",
        func_li_6: "<strong>Дизлайки</strong> — интегрирован <strong>Return YouTube Dislike API</strong> для отображения количества дизлайков в сочетании с официальными данными",
        func_li_7: "<strong>Фильтрация комментариев</strong> — <strong>Ключевые слова</strong> используются для локальной фильтрации комментариев и ответов. YouTube Data API не осуществляет такую фильтрацию",
        func_li_8: "<strong>Проверка квоты</strong> — при запуске делается тестовый запрос, чтобы убедиться, что ваша <strong>квота YouTube API</strong> не превышена до начала работы",
        func_li_9: "<strong>Автоматическая проверка</strong> — перед выполнением запросов к API, YouTube Explorer пингует <code class='inline-code'>google.com</code>, чтобы убедиться, что ваше соединение активно. Если соединение разорвано, вы можете повторить попытку подключения",
        func_li_10: "Получайте подробные сообщения об ошибках, если что-то пойдет не так",
        func_li_11: "Главное меню состоит из двух страниц",
        func_li_12: "Восстановите свой ключ <strong>YouTube API</strong> на второй странице главного меню",

        lic_title: "🖌️Лицензия",
        lic_p1: "YouTube Explorer распространяется под лицензией <code class='inline-code'>GNU GPL-3.0</code>.",
        lic_p2: "Версии, выпущенные до 22-01-2026, распространялись под лицензией <code class='inline-code'>MIT License</code>.",
        lic_p_new: "Версии, выпущенные до 20.05.2026, распространялись под лицензией <code class='inline-code'>Apache-2.0 license</code>",
        lic_p3: "Автор: Валентин Колесников",
        lic_p4: "Оригинальный репозиторий: <a href='https://github.com/valentin-kolesnikov/YouTube_Explorer'>YouTube_Explorer</a>",
        lic_p5: "Для получения более подробной информации смотрите файлы <a href='LICENSE'>LICENSE</a> и <a href='ABOUT'>ABOUT</a>.",

        contr_title: "❤️Сотрудничество",
        contr_p1: "Спасибо за ваш интерес к участию в развитии этого проекта.",
        contr_p2: "Этот проект лицензирован под <strong>General Public License 3.0</strong>. Отправляя pull request, вы соглашаетесь с тем, что ваш вклад будет лицензирован под <code class='inline-code'>GPL-3.0</code>.",
        contr_p3: "Если вы создаете форк или производную работу на основе этого проекта, пожалуйста, укажите четкое авторство в вашем <code class='inline-code'>README</code>.",
        contr_p4: "Рекомендуемый формат указания авторства:",
        contr_p5: "<strong>Оригинальный проект: YouTube Explorer от Валентина Колесникова</strong>",
        contr_p6: "Такое указание авторства помогает избежать путаницы и считается хорошей практикой в open-source.",

        how_title: "🤝Как внести свой вклад",
        how_li_1: "Сделайте форк репозитория.",
        how_li_2: "Создайте отдельную ветку для ваших изменений.",
        how_li_3: "Отправьте pull request с понятным описанием.",
        how_li_4: "Убедитесь, что ваши изменения хорошо задокументированы.",

        don_title: "💰Пожертвования",
        don_p: "Если вы искренне хотите меня поддержать, вот ссылка: <a href='https://www.donationalerts.com/r/valera_koleso' target='_blank' rel='noopener noreferrer'><code class='inline-code'>DonationAlerts</code></a>",

        iss_title: "❓Issues",
        iss_p: "Буду рад увидеть ваши мнения и идеи для новых функций или улучшений. Пожалуйста, сообщайте об ошибках, если они есть. Просто откройте <strong>issues</strong> и удивите меня!",

        rps_title_new: "Камень, Ножницы, Бумага",
        rps_meta: "Логика игры • Python • Интерактив",
        rps_intro_new: "Простая реализация классической игры «Камень, Ножницы, Бумага» на Python. Играйте против одного или двух компьютерных противников в текстовом интерфейсе.",
        rps_feat_title: "Особенности",
        rps_feat_1: "Игровой процесс в терминале.",
        rps_feat_2: "Игра против одного или двух компьютеров.",
        rps_feat_3: "Любое количество раундов с повторными ничьими до победы.",
        rps_feat_4: "Случайные ходы компьютера (используется math.ceil; secrets.choice из списка, созданного random.uniform).",
        rps_feat_5: "Четкая система подсчета очков и отслеживания раундов.",
        rps_how_title: "Как играть",
        rps_how_1: "Откройте файл <code class='inline-code'>.exe</code> или <code class='inline-code'>.py</code>.",
        rps_how_2: "В начале выберите, хотите ли вы играть.",
        rps_how_3: "Выберите количество игроков: <code class='inline-code'>1</code> (вы против компьютера) или <code class='inline-code'>2</code> (вы против двух компьютеров).",
        rps_how_4: "Вы можете выбрать любое количество раундов.",
        rps_how_5: "Выберите ход: камень - цифра <code class='inline-code'>1</code>; бумага - цифра <code class='inline-code'>2</code>; ножницы - цифра <code class='inline-code'>3</code>.",
        rps_how_6: "Игра продолжается до победы в каждом раунде; ничья перезапускает ход.",
        rps_how_7: "Объявление победителя покажет, у кого сколько очков, а затем даст возможность отыграться (даже компьютерам, если игрок определенно проиграл), если у кого-то ничья.",
        rps_note: "Я завершил проект! Если я найду ошибки, я исправлю их как небольшие исправления. Однако их быть не должно.",

        rsa_title_main: "RSA на Python",
        rsa_meta: "Криптография • Математика • Экспериментальный",
        rsa_intro: "Скрипт позволяет шифровать и расшифровывать сообщения, используя пару простых чисел.",
        rsa_clarif_title: "Важное уточнение",
        rsa_clarif_text: "Файл .exe находится в релизах. Этот файл <code class='inline-code'>.exe</code> не содержит вирусов. Он был создан для удобства. Я сделал этот файл благодаря <code class='inline-code'>python -m PyInstaller --onefile ...</code>. Если вы не доверяете файлу <code class='inline-code'>.exe</code>, я рекомендую вам использовать файл <code class='inline-code'>.py</code>.",
        rsa_func_title: "Функциональность",
        rsa_func_list: "<li>Ввод сообщения (английский или русский, на ваш выбор).</li> <li>Преобразование в числовой формат.</li> <li>Генерация ключей (p, q, d, e).</li> <li>Шифрование и дешифрование.</li> <li>Отображение промежуточных шагов.</li>",
        rsa_work_title: "Как это работает?",
        rsa_work_list: "<li>Откройте файл <code class='inline-code'>.exe</code> или файл <code class='inline-code'>.py</code>.</li> <li>Выберите английский или русский язык. 1 или 2 соответственно.</li> <li>Напишите сообщение (одно слово). Вы можете писать как прописные, так и строчные буквы.</li> <li>Выберите желаемое простое число p.</li> <li>Выберите простое число q, которое больше p. Предупреждение: этот код не принимает комбинации (p;q), соответственно: (2;3),(2;5),(2;7),(3;5). Программа попросит вас выбрать другие числа.</li> <li>Программа вычисляет все значения по формулам и одновременно выводит зашифрованное сообщение и расшифровывает его.</li>",
        rsa_warn_title: "Важно: эта реализация предназначена для образовательных целей. Не используйте её в продакшене или в реальных системах безопасности.",
        
        lb_title: "Подобный Блокноту",
        lb_meta: "Продуктивность • Python • CLI Инструмент",
        lb_intro: "<p>Это простой Python скрипт, который интерактивно собирает и отображает список записей от пользователя. Он поддерживает два режима:</p>",
        lb_list: "<li>Основная информация</li> <li>Дополнительная информация</li> <li>Идеально подходит для быстрого сбора структурированных данных из пользовательского ввода.</li>",
        lb_clarif_title: "Важное уточнение",
        lb_clarif_text: "Файл <code class='inline-code'>.exe</code> находится в релизах. Этот <code class='inline-code'>.exe</code> файл не содержит вирусов. Он был создан для удобства. Я сделал этот файл благодаря <code class='inline-code'>python -m PyInstaller --onefile ...</code>. Если вы не доверяете файлу <code class='inline-code'>.exe</code>, я рекомендую вам использовать файл <code class='inline-code'>.py</code>.",
        
        lb_feat_title: "Особенности",
        lb_feat_list: "<li>Интерактивные подсказки CLI</li> <li>Два режима ввода (базовый или с дополнительными деталями)</li> <li>Кастомные стоп-слова для завершения сеанса ввода</li> <li>Аккуратное и нумерованное форматирование вывода</li>",
        
        lb_how_title: "Как использовать?",
        lb_how_list: "<li>Откройте файл <code class='inline-code'>.exe</code> или <code class='inline-code'>.py</code>.</li> <li>Выберите режим: 1 = только основная информация; 2 = основная + дополнительная информация.</li> <li>Чтобы остановить ввод, введите: <code class='inline-code'>stop</code>, <code class='inline-code'>enough</code>, <code class='inline-code'>yes</code>, <code class='inline-code'>-</code> или нажмите <code class='inline-code'>Enter</code>.</li> <li>Скрипт выведет ваши записи в виде отформатированного нумерованного списка.</li>",
        
        lb_footer: "Я завершил этот проект. Если я найду ошибки, я исправлю их как небольшие исправления. Однако их быть не должно."
    }
};